#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# ln fe:SOURCE host:remote_system_ds/disk.i vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

#--------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
    LIB_LOCATION=/usr/lib/one
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
    LIB_LOCATION=$ONE_LOCATION/lib
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../datastore/libfs.sh
source ${DRIVER_PATH}/../../etc/datastore/linstor_un/linstor_un.conf
source ${DRIVER_PATH}/../../datastore/linstor_un/linstor_utils.sh

#-------------------------------------------------------------------------------
# Process destination
#-------------------------------------------------------------------------------

DST_HOST=`arg_host $DST`
DISK_ID=$(echo $DST|awk -F. '{print $NF}')

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $DS_ID | $XPATH \
                    /DATASTORE/TEMPLATE/LS_CONTROLLERS)

LS_CONTROLLERS="${XPATH_ELEMENTS[j++]}"

linstor_load_keys

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

SRC_PATH=`arg_path $SRC`
SRC_RES="$(echo "$SRC_PATH" | $AWK -F/ '{print $(NF-1)}')"
DST_PATH=`arg_path $DST`
DST_DIR=`dirname $DST_PATH`

LINK_CMD=$(cat <<EOF
    set -e -o pipefail
    mkdir -p $DST_DIR
    rm -f $DST_PATH
    ln -s $SRC_PATH $DST_PATH
EOF
)

#-------------------------------------------------------------------------------
# Link the image
#-------------------------------------------------------------------------------

linstor_attach_volume "$DST_HOST" "$SRC_RES" "$DISKLESS_POOL"

ssh_exec_and_log "$DST_HOST" "$LINK_CMD" \
                 "Error linking $SRC_PATH to $DST_PATH on $DST_HOST"

exit 0
