#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# ln fe:SOURCE host:remote_system_ds/disk.i vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the source datastore (0 is the images datastore)

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

#--------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../datastore/libfs.sh
source ${DRIVER_PATH}/../../etc/datastore/linstor_un/linstor_un.conf
source ${DRIVER_PATH}/../../datastore/linstor_un/linstor_utils.sh

#-------------------------------------------------------------------------------
# Process destination
#-------------------------------------------------------------------------------

DS_ID=$(echo $DST | $AWK -F/ '{print $(NF-2)}')
DST_HOST=`arg_host $DST`
DISK_ID=$(echo $DST| $AWK -F. '{print $NF}')

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $DS_ID | $XPATH \
                    /DATASTORE/TEMPLATE/LS_CONTROLLERS \
                    /DATASTORE/TEMPLATE/LS_CERTFILE \
                    /DATASTORE/TEMPLATE/LS_KEYFILE \
                    /DATASTORE/TEMPLATE/LS_CAFILE \
                    /DATASTORE/TEMPLATE/DISKLESS_POOL)

LS_CONTROLLERS="${XPATH_ELEMENTS[j++]}"
LS_CERTFILE="${XPATH_ELEMENTS[j++]}"
LS_KEYFILE="${XPATH_ELEMENTS[j++]}"
LS_CAFILE="${XPATH_ELEMENTS[j++]}"
DISKLESS_POOL="${XPATH_ELEMENTS[j++]:-DfltDisklessStorPool}"

linstor_load_keys

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

SRC_DEV=`arg_path $SRC`
SRC_RES="$(echo "$SRC_DEV" | $AWK -F/ '{print $(NF-1)}')"
DST_PATH=`arg_path $DST`
DST_DIR=`dirname $DST_PATH`

#-------------------------------------------------------------------------------
# Link the image
#-------------------------------------------------------------------------------

# Set properties
linstor_exec_and_log \
    "resource-definition set-property $SRC_RES Aux/one/VM_ID $VM_ID"
linstor_exec_and_log \
    "resource-definition set-property $SRC_RES Aux/one/DS_ID $DS_ID"
linstor_exec_and_log \
    "resource-definition set-property $SRC_RES Aux/one/DISK_ID $DISK_ID"

# Attach diskless resource on destination host
linstor_attach_diskless "$DST_HOST" "$SRC_RES" "$DISKLESS_POOL"

LINK_CMD=$(cat <<EOF
    set -e -o pipefail
    mkdir -p $DST_DIR
    rm -f $DST_PATH
    ln -s $SRC_DEV $DST_PATH
EOF
)

ssh_exec_and_log "$DST_HOST" "$LINK_CMD" \
    "Error linking $SRC_DEV to $DST_PATH on $DST_HOST"

exit 0
