#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# mvds host:remote_system_ds/disk.i fe:SOURCE vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

#--------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../datastore/libfs.sh
source ${DRIVER_PATH}/../../etc/datastore/linstor_un/linstor_un.conf
source ${DRIVER_PATH}/../../datastore/linstor_un/linstor_utils.sh

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $DS_ID | $XPATH \
                    /DATASTORE/TEMPLATE/LS_CONTROLLERS)

LS_CONTROLLERS="${XPATH_ELEMENTS[j++]}"

linstor_load_keys

DISK_ID=$(echo $SRC | $AWK -F. '{print $NF}')

DST_DEV="$DST"
SRC_PATH=`arg_path $SRC`
SRC_HOST=`arg_host $SRC`
DST_RES="$(echo "$DST_DEV" | $AWK -F/ '{print $(NF-1)}')"

#-------------------------------------------------------------------------------
# Unlink the image
#-------------------------------------------------------------------------------

# Detach resource
DST_RES_DISKLESS_HOSTS=$(linstor_get_diskless_hosts_for_res "$DST_RES")
if [[ " $DST_RES_DISKLESS_HOSTS " =~ " $SRC_HOST " ]]; then
    linstor_exec_and_log \
        "resource delete $SRC_HOST $DST_RES --async"
fi

# Unlink device on source host
ssh_exec_and_log_no_error "$SRC_HOST" \
    "rm -f $SRC_PATH" \
    "Error unlinking $SRC_PATH on $SRC_HOST"

# Set properties
linstor_exec_and_log \
    "resource-definition set-property $DST_RES Aux/one/VM_ID"
linstor_exec_and_log \
    "resource-definition set-property $DST_RES Aux/one/DS_ID"
linstor_exec_and_log \
    "resource-definition set-property $DST_RES Aux/one/DISK_ID"
linstor_exec_and_log \
    "resource-definition set-property $DST_RES DrbdOptions/Net/allow-two-primaries yes"

exit 0
